### ISSUE TITLE
mysql: Creating X client connections

### ISSUE THREAD

**Issue by stian-sandvold** [will123195/oreo#33]
When testing oreo for the first time, I set it up against my test-db and during discovery it consumes all free client connections (had standard 152 concurrent connections setup, used all of them).

Tried to limit the user to 10 concurrent, aswell as changing the source code (when that didnt work) to specify the pool's connectionLimit to 10, which it seemed to ignore\bypass quite easily.

Is there something i'm missing, or does it just constantly generate new connections?

**Comment by stian-sandvold** [comment]
Solved this partially by putting the pool variable outside getClient, and checking if it's set or not in getClient (Initialising it if undefined)


Another problem that came to light is that pool connections dont seem to be released; Discovering my test-database with 20 or so tables with just 5 concurrent connections, made the entire process halt as they where all waiting for connections forever.

**Comment by will123195** [comment]
@stian-sandvold I just published version 0.1.5 which should resolve this issue.
