### ISSUE TITLE
mysql: pooled connections are not removed when application is shut down

### ISSUE THREAD

**Issue by stian-sandvold** [will123195/oreo#35]
After starting and stopping the application, the mysql connections used are "sleeping" in the database; When limiting the number of concurrent connections, this quickly becomes a problem after a few restarts.

Could this be the result of some missing configuration again the mysql connector, or the lack of some cleanup routine for when the process closes?

**Comment by stian-sandvold** [comment]
After some research into the mysql connector and some testing, the following code cleans up the connections if the application is closed:

process.on('SIGINT', function() {
  Object.keys(pools).forEach(function(k) { pools[k].end() });
  process.exit();
});

**Comment by will123195** [comment]
Cool thanks!

I think we need something like this also in case the server drops the connection
```js
// remove connection from the pool if the connection disconnects
connection.on('error', function (err) {
  //console.log('connection error: ' + err);
  pool.poolInstance.destroy(connection);
});
```

**Comment by will123195** [comment]
We now have `db.end()` which closes all the db connections.
