### ISSUE TITLE
Full example maybe failed

### ISSUE THREAD

**Issue by g770728y** [will123195/oreo#65]
// Hydrate a book's author (1-to-1 linked row)
        book.hydrate('author')
        .then(() => {
          console.log(book.author) // { id: 1, name: Hunter S. Thompson }
        })

        // Update a book
        book.update({
          title: 'The Rum Diary'
        })
    .    then(book => {
          console.log(book) // { id: 1, title: The Rum Diary, author_id: 1 }
        })

cause exception =>

    Save Error: { table: 'books',
      data:
       Row {
         id: 17,
         title: 'HaHHHHHHHHHHH',
         author_id: undefined,          <===  author_id has become undefined
         something: null,
         author:
          Row {
            id: 17,
            name: 'gouyong',
            books: null,
            Country: null,
            birthDate: null,
            insertedAt: 2018-06-07T12:09:06.000Z } } }
    SQL Error: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'field list'
    Rollback Transaction

If set `author=null` before update, everything is ok:

    // Hydrate a book's author (1-to-1 linked row)
        book.hydrate('author')
        .then(() => {
          console.log(book.author) // { id: 1, name: Hunter S. Thompson }
        })

       book.author = null;          <======= 

        // Update a book
        book.update({
          title: 'The Rum Diary'
        })
    .    then(book => {
          console.log(book) // { id: 1, title: The Rum Diary, author_id: 1 }
        })

I think it's a bug, right?

sorry for language.

BTW, oreo is really cool !

**Comment by will123195** [comment]
Are you using postgres or mysql? what version?

It looks like you may not have a foreign key defined in your schema.

**Comment by g770728y** [comment]
Yes, I use mysql, and forget foreign key.... so sorry... 
Thanks :+1:
